#!/usr/bin/env bash
# Codex emitter (loom registry — see ../loom.sh header).
# Spec pack: harness-specs/codex.md
#
# Emits .codex/config.toml: one [mcp_servers.<name>] table per canonical
# server with tool calls pre-approved. Codex has no hook mechanism and no
# per-tool permission allowlist; every hook event becomes a GAPS row.

emit_codex() {
  local ir="$1" out="$2"
  local dir="${out}/.codex"
  mkdir -p "${dir}"

  local loom_script config_path mcp_json allowlist note
  loom_script="$(jq -r '.meta.loom_script' "${ir}")"
  config_path="$(jq -r '.meta.config_path' "${ir}")"
  mcp_json="$(jq -r '.meta.mcp_json' "${ir}")"
  allowlist="$(jq -r '.meta.allowlist' "${ir}")"
  note="$(jq -r '.meta.mcp_note' "${ir}")"

  {
    echo "# Codex project-scoped configuration. Loads only when the project is marked"
    echo "# trusted (see developers.openai.com/codex/config-advanced)."
    echo "# Generated by loom from ${mcp_json} — do not edit by hand; edit the canonical"
    echo "# config or ${config_path} and re-run ${loom_script}."
    [[ -n "${allowlist}" ]] && echo "# MCP server allowlist source of truth: ${allowlist}"
    [[ -n "${note}" ]] && printf '%s\n' "${note}" | sed 's/^/# /'
    echo
    jq -r '.mcp[] |
      "[mcp_servers.\(.name)]\nurl = \"\(.url)\"\ndefault_tools_approval_mode = \"auto\"\n"' "${ir}"
  } > "${dir}/config.toml"

  local control
  control="$(jq -r '.meta.hook_gap_control | .codex // .default' "${ir}")"
  while IFS= read -r event; do
    [[ -n "${event}" ]] && gap_add codex "hook event: ${event}" "${control}"
  done < <(jq -r '.hooks | keys[]' "${ir}")
}
